version: '3.7'

services:
  web:
    build: .
    command: python redbook_dating/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=1qaz2wsx
      - POSTGRES_DB=redbook_dating

volumes:
  postgres_data:
