# Generated by Django 3.1.2 on 2020-10-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Класс')),
            ],
        ),
        migrations.CreateModel(
            name='SubSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Подкласс')),
                ('parent_species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.species', verbose_name='Родительский класс')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Кличка')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('gender', models.CharField(choices=[('М', 'Man'), ('W', 'Woman')], max_length=1, verbose_name='Пол')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('subspecies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.subspecies', verbose_name='Подкласс')),
            ],
        ),
    ]
